Revert "test"
This reverts commit 1321967976cf8b39ffded65d65ad51985667d67f.

diff --git a/.github/actions/restore_or_install_byond/action.yml b/.github/actions/restore_or_install_byond/action.yml
--- a/.github/actions/restore_or_install_byond/action.yml
+++ b/.github/actions/restore_or_install_byond/action.yml
@@ -29,6 +29,51 @@ runs:
         echo "BYOND_MAJOR=$BYOND_MAJOR" >> $GITHUB_ENV
         echo "BYOND_MINOR=$BYOND_MINOR" >> $GITHUB_ENV
 
+    # Try to grab libcurl from the cache
+    # If we fail, find the nearest server, download it, and upload it to the cache.
+    # Only required for BYOND versions 516.1664+
+    - name: Restore libcurl cache
+      id: restore_libcurl_cache
+      if: env.BYOND_MAJOR >= 516 && env.BYOND_MINOR >= 1664
+      uses: actions/cache/restore@v6.1.0
+      with:
+        path: ~/libcurl-cache
+        key: ${{ runner.os }}-libcurl-i386
+    - name: Apply libcurl cache
+      if: env.BYOND_MAJOR >= 516 && env.BYOND_MINOR >= 1664 && steps.restore_libcurl_cache.outputs.cache-hit == 'true'
+      shell: bash
+      run: |
+        [ -d ~/libcurl-cache/usr/lib ] && sudo cp -a ~/libcurl-cache/usr/lib/* /usr/lib/ || true
+        [ -d ~/libcurl-cache/lib ] && sudo cp -a ~/libcurl-cache/lib/* /lib/ || true
+        sudo ldconfig
+
+    - name: Find fastest APT mirror
+      if: env.BYOND_MAJOR >= 516 && env.BYOND_MINOR >= 1664 && !steps.restore_libcurl_cache.outputs.cache-hit
+      uses: vegardit/fast-apt-mirror.sh@v1
+      with:
+        sample-size: 8192
+        sample-time: 5
+    - name: Install 32-bit libcurl
+      if: env.BYOND_MAJOR >= 516 && env.BYOND_MINOR >= 1664 && !steps.restore_libcurl_cache.outputs.cache-hit
+      shell: bash
+      run: |
+        sudo dpkg --add-architecture i386
+        sudo apt-get update -qq
+        sudo apt-get install -y --no-install-recommends libcurl4t64:i386
+    - name: Prepare libcurl cache
+      if: env.BYOND_MAJOR >= 516 && env.BYOND_MINOR >= 1664 && !steps.restore_libcurl_cache.outputs.cache-hit
+      shell: bash
+      run: |
+        mkdir -p ~/libcurl-cache/usr/lib ~/libcurl-cache/lib
+        [ -d /usr/lib/i386-linux-gnu ] && cp -a /usr/lib/i386-linux-gnu ~/libcurl-cache/usr/lib/ || true
+        [ -d /lib/i386-linux-gnu ] && cp -a /lib/i386-linux-gnu ~/libcurl-cache/lib/ || true
+    - name: Save libcurl cache
+      if: env.BYOND_MAJOR >= 516 && env.BYOND_MINOR >= 1664 && !steps.restore_libcurl_cache.outputs.cache-hit
+      uses: actions/cache/save@v6.1.0
+      with:
+        path: ~/libcurl-cache
+        key: ${{ steps.restore_libcurl_cache.outputs.cache-primary-key }}
+
     # The use of `actions/cache/restore` and `actions/cache/save` here is deliberate, as we want to
     # save the BYOND install to a cache as early as possible. If we used just `actions/cache`, it
     # would only attempt to save the cache at the end of a job. This ensures that if a workflow run
