Add back the tgui binaries for TGS3's benefit

diff --git a/tgui/bin/tgui b/tgui/bin/tgui
--- a/tgui/bin/tgui
+++ b/tgui/bin/tgui
@@ -71,8 +71,6 @@ task-clean() {
   ## Build artifacts
   rm -rf public/.tmp
   rm -f public/*.map
-  rm -f public/*.chunk.*
-  rm -f public/*.bundle.*
   rm -f public/*.hot-update.*
   ## Yarn artifacts
   rm -rf .yarn/cache
@@ -83,6 +81,19 @@ task-clean() {
   ## NPM artifacts
   rm -rf **/node_modules
   rm -f **/package-lock.json
+}
+
+## Validates current build against the build stored in git
+task-validate-build() {
+  cd "${base_dir}"
+  local diff
+  diff="$(git diff public/*)"
+  if [[ -n ${diff} ]]; then
+    echo "Error: our build differs from the build committed into git."
+    echo "Please rebuild tgui."
+    exit 1
+  fi
+  echo "tgui: build is ok"
 }
 
 ## Installs merge drivers and git hooks
@@ -124,6 +135,16 @@ fi
 if [[ ${1} == "--install-git-hooks" ]]; then
   shift 1
   task-install-git-hooks
+  exit 0
+fi
+
+## Continuous integration scenario
+if [[ ${1} == "--ci" ]]; then
+  task-clean
+  task-install
+  task-eslint
+  task-webpack --mode=production
+  task-validate-build
   exit 0
 fi
 
