5 - My rust-g experiment will not work

diff --git a/.github/workflows/ci_suite.yml b/.github/workflows/ci_suite.yml
--- a/.github/workflows/ci_suite.yml
+++ b/.github/workflows/ci_suite.yml
@@ -92,14 +92,14 @@ jobs:
       fail-fast: false
       matrix:
         map: ${{ fromJSON(needs.find_all_maps.outputs.maps).paths }}
-    services:
-      mysql:
-        image: mysql:latest
-        env:
-          MYSQL_ROOT_PASSWORD: root
-        ports:
-          - 3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+    # services:
+    #   mysql:
+    #     image: mysql:latest
+    #     env:
+    #       MYSQL_ROOT_PASSWORD: root
+    #     ports:
+    #       - 3306
+    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
     concurrency:
       group: ci-${{ github.ref }}-${{ matrix.map }}
       cancel-in-progress: true
@@ -117,12 +117,12 @@ jobs:
       #     mysql -u root -proot tg_ci < SQL/tgstation_schema.sql
       #     mysql -u root -proot -e 'CREATE DATABASE tg_ci_prefixed;'
       #     mysql -u root -proot tg_ci_prefixed < SQL/tgstation_schema_prefixed.sql
-      # - name: Install rust-g
-      #   run: |
-      #     sudo dpkg --add-architecture i386
-      #     sudo apt update || true
-      #     sudo apt install -o APT::Immediate-Configure=false libssl1.1:i386
-      #     bash tools/ci/install_rust_g.sh
+      - name: Install rust-g
+        run: |
+          sudo dpkg --add-architecture i386
+          sudo apt update || true
+          sudo apt install -o APT::Immediate-Configure=false libssl1.1:i386
+          bash tools/ci/install_rust_g.sh
       - name: Compile Tests
         run: |
           bash tools/ci/install_byond.sh
